name: Example-next-web-app workflow

on:
  push:
    branches:
      - main

jobs:
  
  build-project:
    runs-on: ubuntu-latest
    name: Build Project
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install NPM dependencies
      run: npm install
    - name: Build project assets
      run: npm run build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: site-artifacts
        path: .next/
  
